import { Button, VerticalBox, SpinBox } from "std-widgets.slint";

export component AppWindow inherits Window {
	in-out property <int> num: 2;
	in-out property <int> step: 2;
	callback more(int);
	VerticalBox {
		Text {
			text: "Counter: \{root.num}";
		}

		Button {
			text: "MUCH MORE!";
			clicked => {
				root.more(root.step);
			}
		}

		SpinBox {
            minimum: 1;
            value: 2;
            edited => {
                root.step = self.value;
            }
		}
	}
}
