import { Button, VerticalBox, SpinBox, ListView, HorizontalBox, ComboBox, GroupBox } from "std-widgets.slint";

export component AppWindow inherits Window {
	in-out property <int> num: 2;
	in-out property <int> step: 2;
	callback more(int);
		VerticalBox {
            Text {
                text: "Choose ramdisk device to perform action";
                vertical-alignment: bottom;
            }
            ComboBox {
	            model: ["/dev/tmpfs", "/home/user/ramdisk","/ramdisk"];
			}
			Text {
			    text: "...Or create a new ramdisk device";
				vertical-alignment: center;
			}
			Text {
			    text: "Size in Megabytes";
				vertical-alignment: bottom;
			}
			SpinBox {
                value: 512;
                step-size: 512;
                maximum: 4096;
                minimum: 512;
            }
            Button {
                text: "Create new";
            }
        }
}
